name = "Forty"
license = "Creative Commons Attribution 3.0"
licenselink = "https://github.com/MarcusVirg/forty/blob/master/LICENSE.md"
description = "A portfolio/blog website built for companies or personal freelancers."
homepage = "//techfinder123.github.com/soltoro-temp"
tags = ["company","blog"]
features = ["blog"]
min_version = "0.55"

[author]
  name = "Hansol Jeong"
  homepage = "https://github.com"

# If porting an existing theme
[original]
  author = "AJ"
  name = "HTML5 Up"
  homepage = "https://html5up.net/forty"
